server:
  port: '8090'

jwtSecret: meetingRoomApplicationSecretKey
jwtExpirationMs: '86400000'
jwtRefreshExpirationMs: '2000000000'

---
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/authorization-service'
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always
  application:
      name: user-identity
  mvc:
    pathmatch:
      # Set the PATH matching policy to solve the high version SpringBoot boot Springfox Empty Pointer Anomaly problem,
      # Specific See: https://blog.csdn.net/faint35799/Article/details/122344731
      matching-strategy: ant_path_matcher
eureka:
  instance:
    appname: user-identity
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
